### ISSUE TITLE
[Question] Onebag and Bagnon seem to be the same addon

### ISSUE THREAD

**Issue by reaktorblue** [NoobTaco/willitclassic-issues#10]
I've been looking for "Onebag3" as my research seems to suggest this addon however, when I look up "onebag" it leads to Bagnon.

Are these the same addon now or should the site be doing this?

**Comment by NoobTaco** [comment]
No, Onebag and Bagnon are different addons. Bagnon is the updated bag.

**Comment by reaktorblue** [comment]
Oh ok, previously when searching for Onebag, the link would take you to Bagnon. Searching for Bagnon would work as one would expect however, Onebag doesn't appear on the site anymore so it appears to have been fixed.

Thanks for clarifying for me, it's greatly appreciated!
