### ISSUE TITLE
weakauras links

### ISSUE THREAD

**Issue by mrbuds** [NoobTaco/willitclassic-issues#5]
Hey there, we have many issues coming from people using your website installing wrong version of WeakAuras.

WeakAuras downloaded from GitHub is not packaged and can't be use directly on classic.
Curseforge link doesn't give a proper classic version download link, users have to go to the "files" tab and select correct version, and most of the time they don't do that.

Could you only list the link for wowinterface for now ?

**Comment by NoobTaco** [comment]
You bet. I have made adjustments to the listing to only reflect the WoWi link.

Keep up the great work on developing over there guys!
