### ISSUE TITLE
[Question] Is there any reason for addon developers to ensure their addons are associated with their account specifically?

### ISSUE THREAD

**Issue by cannonpalms** [NoobTaco/willitclassic-issues#6]
Hi there. I'm the developer of FasterLooting and I noticed about a week ago that someone had added my addon to the list at WillItClassic. I just wanted to reach out and make sure that there isn't some sort of "administrative back-end" I'm missing by having not submitted it myself--e.g. the ability to update links, change the description, or change the thumbnail image. I don't currently have an account on the website, but I don't see any sort of *<Is this your addon? Claim it by clicking here!>*-esque feature either, so I'm unsure of whether or not I need to worry about this.

**Comment by NoobTaco** [comment]
Hi there Cannonpalms. There is not currently a claim system in place, but it is def something I wish to implement for the future. My goal has always been to support the addon authors first as we are all fellow developers.

The site is community-driven, so sometimes false or incorrect data is getting through. The good news is I am the current owner of that record. 

If you would like to create an account I can transfer the listing to you so you can maintain it yourself.

Thanks for reaching out and thank you for your development

**Comment by cannonpalms** [comment]
@NoobTaco Sorry for the radio silence. Classic calls!

I've created an account under cannonpalms(at)me(dot)com. Would you mind transfering the addon to me when you get a chance?

Thanks

**Comment by NoobTaco** [comment]
Listing is transferred to you now. You should have the rights to make edits and updates.
